[project]
name = "searchbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.115.11",
    "gel>=3.1.0",
    "google-genai>=1.25.0",
    "requests>=2.32.3",
]
